### ISSUE TITLE
ESPCheck doesn't work

### ISSUE THREAD

**Issue by AyazJenkins** [Photon-GitHub/AntiCheatAddition#543]
Log:
[08:28:32 INFO]: [AntiCheatAddition] floodgate not found
[08:28:32 INFO]: [AntiCheatAddition] BrandHider has been enabled.
[08:28:32 INFO]: [AntiCheatAddition] DamageIndicator has been enabled.
[08:28:32 INFO]: [AntiCheatAddition] EnchantmentHider has been enabled.
[08:28:32 INFO]: [AntiCheatAddition] Esp has been enabled.
[08:28:32 INFO]: [AntiCheatAddition] ESP | Default entity tracking range found.
[08:28:32 INFO]: [AntiCheatAddition] LogBot has been disabled in the config.
Config: 
```
  Esp:
  # Do you want to enable anti - ESP?
  #
  # If your server has a lot of players in one world within its render distance the ESP check will create a medium to
  # high CPU load.
  #
  # If you create new worlds make sure to restart your server to make ESP cover the new worlds.
  enabled: true
  # How many ticks shall be waited between two ESP cycles. Setting this too low may result in performance issues,
  # setting it too high may result in players being hidden too long and popping up.
  interval_ticks: 2
  # As defined above, only sneaking players are fully hidden from other players as otherwise one could see their
  # location thanks to nametags. If you disable nametags or choose to ignore this vanilla behaviour, you can set
  # this option to true which will cause all players to be fully hidden, even when not sneaking. Indeed, this will
  # make Esp much more effective against eps, tracers and similar cheats.
  only_full_hide: true
  # This determines whether minecraft's 3rd person modes should be considered for calculation as well.
  # Disabling this will reduce the required number of block queries by two thirds.
  # Especially useful if you have games in which players are not supposed to use the third person mode.
  calculate_third_person_modes: true`
```
Server: Purpur 1.19.3
Plugins: AntiCheatAddition, AuthMe, CoreProtect, GrimAC, LibertyBans, LuckPerms, Multiverse-Core, PL-Hide, PlaceholderAPI, ProtocolLib, SkinsRestorer, spark, StaffPlus
![resim](https://user-images.githubusercontent.com/67198542/214861735-0d5b3352-692e-48d3-a190-c4ce570a1369.png)
